# Generated by Django 4.1.4 on 2023-01-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_unique_together_users_key_words_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user',
            new_name='user_name',
        ),
    ]
