# Generated by Django 4.1.4 on 2023-01-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_users_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='user',
        ),
    ]
