# Generated by Django 4.1.4 on 2023-01-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profileuser_tickers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfileUser',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
