# Generated by Django 4.1.3 on 2022-11-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=8)),
                ('volume', models.DecimalField(decimal_places=6, max_digits=24)),
                ('volume_weighted', models.DecimalField(decimal_places=6, max_digits=24)),
                ('open_price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('close_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('highest_price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('lowest_price', models.DecimalField(decimal_places=6, max_digits=16)),
                ('time', models.CharField(max_length=1028)),
                ('num_transactions', models.IntegerField()),
            ],
        ),
    ]
