# Generated by Django 4.1.3 on 2022-12-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrregularStocksDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=24)),
                ('volume', models.DecimalField(decimal_places=6, max_digits=24)),
                ('avg_volume', models.DecimalField(decimal_places=6, max_digits=24)),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
