# Generated by Django 4.1.3 on 2022-12-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='irregularstocksdates',
            unique_together={('ticker', 'time')},
        ),
    ]
