# Generated by Django 3.2.8 on 2022-12-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_irregularstocksdates10'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrregularStocksDates5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=24)),
                ('volume', models.DecimalField(decimal_places=6, max_digits=24)),
                ('avg_volume', models.DecimalField(decimal_places=6, max_digits=24)),
                ('time', models.DateTimeField(null=True)),
            ],
            options={
                'unique_together': {('ticker', 'time')},
            },
        ),
    ]
