# Generated by Django 4.1.3 on 2022-12-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_irregularstocksdates10_dev_volume_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IrregularStocksDates5',
        ),
    ]
