# Generated by Django 4.1.3 on 2022-12-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_delete_irregularstocksdates5'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IrregularStocksDates10',
        ),
    ]
