# Generated by Django 4.1.3 on 2022-12-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_delete_irregularstocksdates10'),
    ]

    operations = [
        migrations.AddField(
            model_name='irregularstocksdates',
            name='dev_volume',
            field=models.DecimalField(decimal_places=6, max_digits=15, null=True),
        ),
    ]
