# Generated by Django 3.2.8 on 2022-12-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_irregularstocksdates_dev_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='irregularstocksdates',
            name='rating',
            field=models.DecimalField(decimal_places=4, max_digits=4, null=True),
        ),
    ]
