# Generated by Django 3.2.8 on 2022-12-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_irregularstocksdates_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irregularstocksdates',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
