# Generated by Django 4.1.4 on 2023-01-06 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0013_stocklist_userstock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocklist',
            unique_together={('ticker',)},
        ),
        migrations.AlterUniqueTogether(
            name='userstock',
            unique_together={('user', 'stock')},
        ),
    ]
